migrating to androidX
Joran-Dob/spotify-playback-flutter pull request #34
Opened 2019-09-03 18:18 UTC by jobehi

- Migrating to android X
- incrementing the major version as mentioned in the[ pub guidelines](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#for-plugin-maintainers-migrating-a-flutter-plugin-to-androidx) 

Also this is my first time doing a pull request, I don't know if I'm doing it right :))

2019-09-05 14:43 UTC, Joran-Dob requested changes
The version bump should not go to version 0.1.0. please change it to 0.0.9.

Thanks 🎊

2019-09-07 14:27 UTC, jobehi commented
> The version bump should not go to version 0.1.0. please change it to 0.0.9.
> 
> Thanks 🎊

The problem is that it's a breaking change that requires a manual migration for current users : 

like explained here : [https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#for-plugin-maintainers-migrating-a-flutter-plugin-to-androidx](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#for-plugin-maintainers-migrating-a-flutter-plugin-to-androidx)

> Make sure to increment the major version of your plugin for this change and clearly document it in your plugin’s changelog. This breaking change requires manual migration for users to fix. Pub treats digits differently depending on whether a plugin is pre- or post-1.0.0. The very first digit is the major version for plugins that are at or above 1.0.0. For plugins below 1.0.0, the middle digit is considered to the major version.

2019-09-10 09:39 UTC, Joran-Dob commented
Thanks for the info @jobehi I wasnt aware. 👍

2019-09-10 09:40 UTC, Joran-Dob approved these changes

2019-09-10 09:40 UTC, Joran-Dob approved these changes

2019-09-10 09:40 UTC, merged